-- Construct raw schema

BEGIN;

CREATE SCHEMA IF NOT EXISTS raw;

-- ============================================================
-- 1. Publication / extraction era metadata
-- ============================================================

CREATE TABLE raw.g6_era (
    era_id                      smallint PRIMARY KEY,
    first_document_date         date NOT NULL,
    last_document_date          date NOT NULL,
    source_reported_doc_count   smallint,
    era_description             text NOT NULL,

    CONSTRAINT ck_g6_era_id
        CHECK (era_id BETWEEN 1 AND 8),

    CONSTRAINT ck_g6_era_dates
        CHECK (first_document_date <= last_document_date)
);


-- ============================================================
-- 2. Logical monthly G.6 release
-- ============================================================

CREATE TABLE raw.g6_release (
    g6_release_id       smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_cycle_month date NOT NULL,
    publication_code    text NOT NULL DEFAULT 'G.6',
    release_title       text NOT NULL
        DEFAULT 'Debits and Deposit Turnover at Commercial Banks',
    era_id              smallint NOT NULL,
    release_notes       text,
    created_at          timestamptz NOT NULL DEFAULT current_timestamp,

    CONSTRAINT fk_g6_release_era
        FOREIGN KEY (era_id)
        REFERENCES raw.g6_era (era_id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_g6_release_cycle
        UNIQUE (publication_code, release_cycle_month),

    CONSTRAINT ck_release_cycle_first_day
        CHECK (EXTRACT(DAY FROM release_cycle_month) = 1)
);


-- ============================================================
-- 3. Individual PDF or other source file
-- ============================================================

CREATE TABLE raw.source_document (
    source_document_id             smallint GENERATED BY DEFAULT AS IDENTITY
                                   PRIMARY KEY,
    g6_release_id                  smallint NOT NULL,
    document_date                  date NOT NULL,
    source_filename                text NOT NULL,
    source_relative_path           text NOT NULL,
    source_format                  text NOT NULL DEFAULT 'pdf',

    document_version               smallint NOT NULL DEFAULT 1,
    version_type                   text NOT NULL DEFAULT 'original',
    is_preferred_version           boolean NOT NULL DEFAULT true,
    supersedes_source_document_id  smallint,

    page_count                     smallint,
    source_notes                   text,
    created_at                     timestamptz NOT NULL DEFAULT current_timestamp,

    CONSTRAINT fk_source_document_release
        FOREIGN KEY (g6_release_id)
        REFERENCES raw.g6_release (g6_release_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_source_document_supersedes
        FOREIGN KEY (supersedes_source_document_id)
        REFERENCES raw.source_document (source_document_id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_source_document_path
        UNIQUE (source_relative_path),

    CONSTRAINT uq_document_version
        UNIQUE (g6_release_id, document_version),

    CONSTRAINT ck_document_version_positive
        CHECK (document_version > 0),

    CONSTRAINT ck_source_document_version_type
        CHECK (
            version_type IN (
                'original',
                'revised',
                'corrected',
                'replacement',
                'unknown'
            )
        ),

    CONSTRAINT ck_source_document_page_count
        CHECK (page_count IS NULL OR page_count > 0)
);

-- No release may have more than one preferred source document.
CREATE UNIQUE INDEX uq_one_preferred_document_per_release
    ON raw.source_document (g6_release_id)
    WHERE is_preferred_version;


-- ============================================================
-- 4. One execution of the Python extraction pipeline
-- ============================================================

CREATE TABLE raw.extraction_run (
    extraction_run_id     smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_label             text NOT NULL UNIQUE,
    pipeline_version      text NOT NULL,
    input_root            text,
    full_corpus_completed boolean NOT NULL DEFAULT false,

    -- JSON array describing each JSONL part:
    -- filename, byte count, and line count.
    input_artifact_manifest jsonb NOT NULL DEFAULT '[]'::jsonb,

    cleanup_report_path   text,
    run_notes             text,
    loaded_at             timestamptz NOT NULL DEFAULT current_timestamp,

    CONSTRAINT ck_extraction_manifest_array
        CHECK (jsonb_typeof(input_artifact_manifest) = 'array')
);


-- ============================================================
-- 5. One JSONL page object
-- ============================================================

CREATE TABLE raw.source_page_extraction (
    source_page_extraction_id smallint GENERATED BY DEFAULT AS IDENTITY
                              PRIMARY KEY,
    source_document_id        smallint NOT NULL,
    extraction_run_id         smallint NOT NULL,
    page_number               smallint NOT NULL,

    input_part_name           text NOT NULL,
    input_line_number         smallint NOT NULL,
    page_classification       text NOT NULL,
    classification_score      double precision,
    classification_reason     text,

    printed_release_code      text,
    printed_release_title     text,
    printed_release_date      date,
    page_adjustment_status    text NOT NULL,

    mean_ocr_confidence       double precision,

    raw_ocr_text              text,
    sparse_ocr_text           text,
    embedded_locator_text     text,

    date_reconciliation       jsonb NOT NULL DEFAULT '{}'::jsonb,
    rendered_ocr_words        jsonb NOT NULL DEFAULT '[]'::jsonb,
    sparse_ocr_words          jsonb NOT NULL DEFAULT '[]'::jsonb,
    embedded_locator_words    jsonb NOT NULL DEFAULT '[]'::jsonb,
    table_anchors             jsonb NOT NULL DEFAULT '[]'::jsonb,
    table_structure           jsonb NOT NULL DEFAULT '[]'::jsonb,

    created_at                timestamptz NOT NULL DEFAULT current_timestamp,

    CONSTRAINT fk_page_source_document
        FOREIGN KEY (source_document_id)
        REFERENCES raw.source_document (source_document_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_page_extraction_run
        FOREIGN KEY (extraction_run_id)
        REFERENCES raw.extraction_run (extraction_run_id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_page_per_document_run
        UNIQUE (source_document_id, extraction_run_id, page_number),

    -- Supports the composite foreign key from g6_cell_extraction.
    CONSTRAINT uq_page_cell_reference
        UNIQUE (
            source_page_extraction_id,
            source_document_id,
            page_number
        ),

    CONSTRAINT ck_page_number_positive
        CHECK (page_number > 0),

    CONSTRAINT ck_jsonl_line_positive
        CHECK (input_line_number > 0),

    CONSTRAINT ck_page_classification
        CHECK (
            page_classification IN (
                'table_page',
                'metadata_page',
                'unrelated_release_page',
                'uncertain_page'
            )
        ),

    CONSTRAINT ck_page_adjustment_status
        CHECK (
            page_adjustment_status IN ('SA', 'NSA', 'unknown')
        ),

    CONSTRAINT ck_date_reconciliation_object
        CHECK (jsonb_typeof(date_reconciliation) = 'object'),

    CONSTRAINT ck_rendered_words_array
        CHECK (jsonb_typeof(rendered_ocr_words) = 'array'),

    CONSTRAINT ck_sparse_words_array
        CHECK (jsonb_typeof(sparse_ocr_words) = 'array'),

    CONSTRAINT ck_embedded_words_array
        CHECK (jsonb_typeof(embedded_locator_words) = 'array'),

    CONSTRAINT ck_table_anchors_array
        CHECK (jsonb_typeof(table_anchors) = 'array'),

    CONSTRAINT ck_table_structure_array
        CHECK (jsonb_typeof(table_structure) = 'array')
);


-- ============================================================
-- 6. One physical observation cell
-- ============================================================

CREATE TABLE raw.g6_cell_extraction (
    g6_cell_extraction_id     integer GENERATED BY DEFAULT AS IDENTITY
                              PRIMARY KEY,

    source_page_extraction_id smallint NOT NULL,
    source_document_id        smallint NOT NULL,
    page_number               smallint NOT NULL,

    table_number              smallint NOT NULL,
    table_instance_id         text NOT NULL,
    row_index                 integer NOT NULL,
    column_index              integer NOT NULL,

    physical_row_center       double precision,
    physical_row_bounds       jsonb NOT NULL,
    cell_bbox                 jsonb NOT NULL,
    ink_density               double precision,

    row_label_raw             text,
    matched_month_label_candidates jsonb NOT NULL DEFAULT '[]'::jsonb,

    -- This is the date assigned by the Python pipeline.
    -- It is preserved as raw pipeline output, not yet treated as
    -- an authoritative economic observation date.
    pipeline_observation_date date,
    observation_date_status   text,
    observation_date_source   text,

    column_path               jsonb NOT NULL,
    canonical_column          jsonb NOT NULL,

    -- Cell-level outcome, but no numeric value is stored here.
    pipeline_cell_status      text NOT NULL,
    pipeline_selection_reason text,

    cross_release_support_count integer NOT NULL DEFAULT 0,
    adjacent_release_values   jsonb NOT NULL DEFAULT '[]'::jsonb,
    validation_flags          jsonb NOT NULL DEFAULT '[]'::jsonb,

    arithmetic_selection      jsonb,
    cross_release_selection   jsonb,

    created_at                timestamptz NOT NULL DEFAULT current_timestamp,

    CONSTRAINT fk_cell_page_and_document
        FOREIGN KEY (
            source_page_extraction_id,
            source_document_id,
            page_number
        )
        REFERENCES raw.source_page_extraction (
            source_page_extraction_id,
            source_document_id,
            page_number
        )
        ON DELETE RESTRICT,

    CONSTRAINT uq_physical_cell
        UNIQUE (
            source_page_extraction_id,
            table_instance_id,
            row_index,
            column_index
        ),

    CONSTRAINT ck_physical_row_bounds_array
        CHECK (jsonb_typeof(physical_row_bounds) = 'array'),

    CONSTRAINT ck_cell_bbox_array
        CHECK (jsonb_typeof(cell_bbox) = 'array'),

    CONSTRAINT ck_matched_month_labels_array
        CHECK (
            jsonb_typeof(matched_month_label_candidates) = 'array'
        ),


    CONSTRAINT ck_column_path_array
        CHECK (jsonb_typeof(column_path) = 'array'),

    CONSTRAINT ck_canonical_column_object
        CHECK (jsonb_typeof(canonical_column) = 'object'),

    CONSTRAINT ck_pipeline_cell_status
        CHECK (
            pipeline_cell_status IN (
                'reported',
                'not_available',
                'blank',
                'extraction_error'
            )
        ),

    CONSTRAINT ck_cell_indices
        CHECK (
            page_number > 0
            AND table_number > 0
            AND row_index >= 0
            AND column_index >= 0
        ),

    CONSTRAINT ck_cross_release_support_nonnegative
        CHECK (cross_release_support_count >= 0)
);


-- ============================================================
-- 7. Every candidate interpretation of a physical cell
-- ============================================================

CREATE TABLE raw.g6_ocr_candidate (
    g6_ocr_candidate_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    g6_cell_extraction_id integer NOT NULL,
    candidate_order       integer NOT NULL,

    ocr_source             text NOT NULL,
    ocr_variant            text,
    raw_recognized_string  text,

    candidate_numeric      numeric,
    candidate_status       text NOT NULL,

    ocr_confidence         double precision,
    normalization_rule     text,

    is_eligible            boolean NOT NULL,
    is_selected            boolean NOT NULL DEFAULT false,
    selection_reason       text,

    measure_canonical      text,

    unsafe_decimal_relocation boolean,
    trimmed_trailing_digits  integer,
    supporting_raw_strings   jsonb,

    created_at               timestamptz NOT NULL DEFAULT current_timestamp,

    CONSTRAINT fk_candidate_cell
        FOREIGN KEY (g6_cell_extraction_id)
        REFERENCES raw.g6_cell_extraction (g6_cell_extraction_id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_candidate_order
        UNIQUE (g6_cell_extraction_id, candidate_order),

    CONSTRAINT ck_candidate_order
        CHECK (candidate_order >= 0),

    CONSTRAINT ck_candidate_status
        CHECK (
            candidate_status IN (
                'reported',
                'not_available',
                'blank',
                'extraction_error'
            )
        ),

    CONSTRAINT ck_candidate_selected_eligible
        CHECK (NOT is_selected OR is_eligible)
);

-- At most one candidate can be selected for one cell.
CREATE UNIQUE INDEX uq_one_selected_candidate_per_cell
    ON raw.g6_ocr_candidate (g6_cell_extraction_id)
    WHERE is_selected;


-- Useful foreign-key lookup indexes.
CREATE INDEX ix_source_document_release
    ON raw.source_document (g6_release_id);

CREATE INDEX ix_page_document
    ON raw.source_page_extraction (source_document_id, page_number);

CREATE INDEX ix_cell_document_page
    ON raw.g6_cell_extraction (
        source_document_id,
        page_number,
        table_instance_id
    );

CREATE INDEX ix_candidate_cell
    ON raw.g6_ocr_candidate (g6_cell_extraction_id);

COMMIT;
